obj-$(CONFIG_SENSORS_SSC)	+= sensors_ssc.o
obj-$(CONFIG_SENSORS_CORE)	+= sensors_core.o

# acclerometer_sensor
obj-$(CONFIG_SENSORS_LIS2DS)		+= lis2ds_core.o
obj-$(CONFIG_SENSORS_LIS2DS_I2C)	+= lis2ds_i2c.o

# optical_sensor
obj-$(CONFIG_SENSORS_CM36686)	+= cm36686.o
obj-$(CONFIG_SENSORS_STK3328)	+= stk3328.o

# magnetic_sensor
obj-$(CONFIG_SENSORS_YAS539)	+= yas_mag_drv-yas539.o yas_mag_kernel.o

# STM sensor
obj-$(CONFIG_SENSORS_LSM6DSL)	+= lsm6dsl_core.o
obj-$(CONFIG_SENSORS_LSM6DSL_I2C)	+= lsm6dsl_i2c.o
obj-$(CONFIG_SENSORS_LSM6DSL_SPI)	+= lsm6dsl_spi.o
